var GAME_LEVELS = [
  ["x                                                                                                         x",
   "x     @                        t                                                                         ox",
   "x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                  xvxx                       xvxxxvxxxvxxxvxxxvxxxvxxxvxxxvxxxvxxxvxxxvx x",
   "x                                      xx                                                                 x",
   "x                          xxxx          xxxxx                                                            x",
   "x        b               xv                  x                v           v       v   v                   x",
   "x                        x                     x                                                          x",
   "x                       x       b xxxxxxxxxxxxxxx                      v                       v   v      x",
   "x                      x          x                                                        v              x",
   "x                     x           x                                v                                      x",
   "x                    x xxx   xxxxxxxxxx                                                                   x",
   "x                   x                 x          xxxx                                                     x",
   "x                  x                  x              x                                                    x",
   "x                 x                   x               x                                                   x",
   "x                x     xxxxxxxx       x       x        x                                                  x",
   "x               x      x              x        x        x                                                 x",
   "x              x       x              x                  x                                                x",
   "x             x        x           =               x      x                                               x",
   "x            x         x         =                         x                                              x",
   "x           x          x          xxxxxx                    x                                             x",
   "x          x           x               x                     x                                            x",
   "x         x            x               x                x     x                                    x!!!!!!x",
   "xxxxxxxxxxx!!!!!!!!xx!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",],
  ["xv   b    x",
   "x         x",
   "x        ox",
   "x       xxx",
   "x        vx",
   "x         x",
   "xo        x",
   "xxx       x",
   "xv        x",
   "x         x",
   "x        ox",
   "x       xxx",
   "x        vx",
   "x         x",
   "xo        x",
   "xxx       x",
   "xv        x",
   "x         x",
   "x        ox",
   "x       xxx",
   "x         x",
   "x         x",
   "xo        x",
   "xxx       x",
   "x         x",
   "x@    t a x",
   "xxxxxxxxxxx",],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxxxvxxxxxvxxxxxvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxx o xxxxxxxxxxxxxxxxxxxxx o xxxxxxxxxxxxx xxxxx xxxxx xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                        x  =            x                                             b                                                                                                         ",
   "x                                                                                              o     o     o     o                                                                                               ",
   "x       x           = xxxxxxx               = xxxxxx            o     o     o     o           o  o  o  o  o  o  o  o                                                                                             ",
   "x @   xxxxxx   xxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxx                                    o     o     o     o     o    t   ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
   "xxxxxxxxxxxx   xxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxx                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxx!!!xxx!!!xxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

   ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xx            xxxxxxxxxxxoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xx  @         xxxxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxx",
    "xxxxxxxxxxtxxxxxx                                         ax                   ",
    "xo                       xx                                x     x=            ",
    "x                          xxxxxxxxx   b    xxxxxxxxxxxxxxxx    xxxx   xxxxxxxx",
    "xxxxxxxxxxxxxxxx   =               oxxxx      oxxxxxxvxvxvx    xx             =",
    "x               xxxxxxxxx           xxxvx      xvxvx          x x            = ",
    "x                           xxxxxxxxxxx xxxxxxx              x  x           =  ",
    "x  o o o     xx                                             x   x          =   ",
    "x      =       xxx                                         x    x          o   ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],


   ["                                                                    ",
    "       x             x x  x    x  x    x xxxxx xxxxx                ",
    "        x     x     x     x x  x  x x  x x     x    x               ",
    "         x   x x   x   x  x  x x  x  x x xxx   xxxxx                ",
    "          x x   x x    x  x   xx  x   xx x     x  x                 ",
    "           x     x     x  x    x  x    x xxxxx x   x                ",
    "                                                                    ",
    " @          t   a                                                     b",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
